name: ecommerce_app
description: A simple to-do list app with Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

  # UI dependencies
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_native_splash: ^2.4.7
  firebase_auth: ^5.7.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png
  web:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png
